### ISSUE TITLE
Typo in Buffer Design Description

### ISSUE THREAD

**Issue by NevadaMark** [ajn96/iSensor-SPI-Buffer#12]
Just FYI, minor typo in this description.   
![BufferDesign_1](https://user-images.githubusercontent.com/12829744/88962271-35456100-d274-11ea-8917-01807fbefdfb.PNG)

**Comment by ajn96** [comment]
Thanks for the catch, fixed. If you spot small errors in the future feel free to edit the documentation to fix it. Github has a pretty good in-browser editor (top right when you click on the file).
