### ISSUE TITLE
Add test points to enable debugging the IMU-Buffer Board SPI Port

### ISSUE THREAD

**Issue by juchong** [ajn96/iSensor-SPI-Buffer#13]

**Comment by juchong** [comment]
The addition of the 16-pin connector should provide a good spot to easily solder in test points.

**Comment by ajn96** [comment]
Not currently in the rev C hardware design. Need to decide if test points for the SPI lines are still necessary

**Comment by ajn96** [comment]
Rev C board design will not include IMU SPI test points
